package org.vaadin.example.npe;


import org.springframework.beans.factory.annotation.Autowired;

import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.router.PreserveOnRefresh;
import com.vaadin.flow.router.Route;

@PreserveOnRefresh
@Route("form")
public class MainViewNPE extends FormLayout {

    public MainViewNPE(@Autowired OrderServiceNPE orderServiceNPE) {
        Grid<OrderNPE> orderGrid = new Grid<>(OrderNPE.class);
        orderGrid.setItems(orderServiceNPE.getOrders());
        add(orderGrid);
    }

    // 2021-05-19 23:05:01.715  INFO 10530 --- [nio-8080-exec-7] o.v.e.preserve_on_refresh.OrderService   : Orders loaded
    //2021-05-19 23:05:19.484 ERROR 10530 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[springServlet]        : Servlet.service() for servlet [springServlet] threw exception
    //
    //java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "windowName" is null
    //	at com.vaadin.flow.spring.scopes.VaadinRouteScope$RouteBeanStore.resetUI(VaadinRouteScope.java:312) ~[vaadin-spring-18.0-SNAPSHOT.jar:na]
    //	at com.vaadin.flow.spring.scopes.VaadinRouteScope$RouteBeanStore.onComponentEvent(VaadinRouteScope.java:279) ~[vaadin-spring-18.0-SNAPSHOT.jar:na]
    //	at com.vaadin.flow.spring.scopes.VaadinRouteScope$RouteBeanStore.onComponentEvent(VaadinRouteScope.java:258) ~[vaadin-spring-18.0-SNAPSHOT.jar:na]
    //	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:205) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:194) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.component.Component.fireEvent(Component.java:377) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.component.ComponentUtil.fireEvent(ComponentUtil.java:385) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.component.ComponentUtil.onComponentDetach(ComponentUtil.java:263) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at java.base/java.util.Optional.ifPresent(Optional.java:176) ~[na:na]
    //	at com.vaadin.flow.internal.nodefeature.ComponentMapping.onDetach(ComponentMapping.java:109) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
    //	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
    //	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:na]
    //	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
    //	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
    //	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
    //	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
    //	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
    //	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
    //	at com.vaadin.flow.internal.StateNode.forEachFeature(StateNode.java:351) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.internal.StateNode.fireDetachListeners(StateNode.java:837) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.internal.StateNode.onDetach(StateNode.java:341) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.internal.StateNode.setParent(StateNode.java:280) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.internal.StateTree$RootNode.setParent(StateTree.java:65) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.component.internal.UIInternals.setSession(UIInternals.java:403) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.server.VaadinSession.removeUI(VaadinSession.java:595) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.server.VaadinService.lambda$removeClosedUIs$20ed7015$1(VaadinService.java:1328) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.component.UI.accessSynchronously(UI.java:446) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.component.UI.accessSynchronously(UI.java:407) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.server.VaadinService.removeClosedUIs(VaadinService.java:1326) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.server.VaadinService.cleanupSession(VaadinService.java:1290) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1490) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1570) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:299) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:109) ~[vaadin-spring-18.0-SNAPSHOT.jar:na]
    //	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
    //	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:710) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:457) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) ~[spring-webmvc-5.3.6.jar:5.3.6]
    //	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177) ~[spring-webmvc-5.3.6.jar:5.3.6]
    //	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52) ~[spring-webmvc-5.3.6.jar:5.3.6]
    //	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060) ~[spring-webmvc-5.3.6.jar:5.3.6]
    //	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962) ~[spring-webmvc-5.3.6.jar:5.3.6]
    //	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.6.jar:5.3.6]
    //	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.6.jar:5.3.6]
    //	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665) ~[javax.servlet-api-4.0.1.jar:4.0.1]
    //	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.6.jar:5.3.6]
    //	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
    //	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.6.jar:5.3.6]
    //	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.6.jar:5.3.6]
    //	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.6.jar:5.3.6]
    //	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.6.jar:5.3.6]
    //	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.6.jar:5.3.6]
    //	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.6.jar:5.3.6]
    //	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
    //	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
    //	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
    //
    //2021-05-19 23:05:19.486 ERROR 10530 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "windowName" is null] with root cause
    //
    //java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "windowName" is null
    //	at com.vaadin.flow.spring.scopes.VaadinRouteScope$RouteBeanStore.resetUI(VaadinRouteScope.java:312) ~[vaadin-spring-18.0-SNAPSHOT.jar:na]
    //	at com.vaadin.flow.spring.scopes.VaadinRouteScope$RouteBeanStore.onComponentEvent(VaadinRouteScope.java:279) ~[vaadin-spring-18.0-SNAPSHOT.jar:na]
    //	at com.vaadin.flow.spring.scopes.VaadinRouteScope$RouteBeanStore.onComponentEvent(VaadinRouteScope.java:258) ~[vaadin-spring-18.0-SNAPSHOT.jar:na]
    //	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:205) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:194) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.component.Component.fireEvent(Component.java:377) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.component.ComponentUtil.fireEvent(ComponentUtil.java:385) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.component.ComponentUtil.onComponentDetach(ComponentUtil.java:263) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at java.base/java.util.Optional.ifPresent(Optional.java:176) ~[na:na]
    //	at com.vaadin.flow.internal.nodefeature.ComponentMapping.onDetach(ComponentMapping.java:109) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
    //	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
    //	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:na]
    //	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
    //	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
    //	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
    //	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
    //	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
    //	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
    //	at com.vaadin.flow.internal.StateNode.forEachFeature(StateNode.java:351) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.internal.StateNode.fireDetachListeners(StateNode.java:837) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.internal.StateNode.onDetach(StateNode.java:341) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.internal.StateNode.setParent(StateNode.java:280) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.internal.StateTree$RootNode.setParent(StateTree.java:65) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.component.internal.UIInternals.setSession(UIInternals.java:403) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.server.VaadinSession.removeUI(VaadinSession.java:595) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.server.VaadinService.lambda$removeClosedUIs$20ed7015$1(VaadinService.java:1328) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.component.UI.accessSynchronously(UI.java:446) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.component.UI.accessSynchronously(UI.java:407) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.server.VaadinService.removeClosedUIs(VaadinService.java:1326) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.server.VaadinService.cleanupSession(VaadinService.java:1290) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1490) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1570) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:299) ~[flow-server-8.0.0.alpha2.jar:8.0.0.alpha2]
    //	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:109) ~[vaadin-spring-18.0-SNAPSHOT.jar:na]
    //	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
    //	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:710) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:457) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) ~[spring-webmvc-5.3.6.jar:5.3.6]
    //	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177) ~[spring-webmvc-5.3.6.jar:5.3.6]
    //	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52) ~[spring-webmvc-5.3.6.jar:5.3.6]
    //	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060) ~[spring-webmvc-5.3.6.jar:5.3.6]
    //	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962) ~[spring-webmvc-5.3.6.jar:5.3.6]
    //	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.6.jar:5.3.6]
    //	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.6.jar:5.3.6]
    //	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665) ~[javax.servlet-api-4.0.1.jar:4.0.1]
    //	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.6.jar:5.3.6]
    //	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
    //	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.6.jar:5.3.6]
    //	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.6.jar:5.3.6]
    //	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.6.jar:5.3.6]
    //	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.6.jar:5.3.6]
    //	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.6.jar:5.3.6]
    //	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.6.jar:5.3.6]
    //	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
    //	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
    //	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
    //	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
    //
    //2021-05-19 23:05:33.892  WARN 10530 --- [alina-utility-1] com.vaadin.flow.server.VaadinSession     : A VaadinSession instance not associated to any service is getting unbound. Session destroy events will not be fired and UIs in the session will not get detached. This might happen if a session is deserialized but never used before it expires.
}
